<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-27 at 11:03:27.
 */

Yii::import('ext.doctrineOrm.DDoctrineContainer');

class DDoctrineContainerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PHPUnit_Framework_MockObject_MockObject 
     */
    protected $container;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
        $this->container = $this->getMockBuilder('DDoctrineContainer')
                                ->setMethods(array('setDDoctrineAutoload'))
                                ->getMock();
    }

    public function testInit_WhenIsNotInicialized_ShouldCallDDoctrineAutoload()
    {
        $this->container->expects($this->once())
                ->method('setDDoctrineAutoload');
        $this->container->init();
    }
    
    public function testInit_WhenIsInicialized_ShouldCallDDoctrineAutoloadJustOnce()
    {
        $this->container->expects($this->once())
                ->method('setDDoctrineAutoload');
        
        $this->container->init();
        $this->container->init();
    }
    
    public function testMappingType_IfTypeIsNotXMLOrAnnotationOrYAML_ShouldThrowInvalidArgumentException()
    {
        $this->setExpectedException('InvalidArgumentException');
        $this->container->setMappingType('badType');
    }

}

?>